version: '3'
services:
  mongo1:
    image: "mongo"
    ports:
      - "27020:27017"
    volumes:
      - $HOME/workspace/irqa-test/mongodb/db1:/data/db
    networks:
      - mongo-networks
    command: mongod --replSet replication
  mongo2:
    image: "mongo"
    ports:
      - "27021:27017"
    volumes:
      - $HOME/workspace/irqa-test/mongodb/db2:/data/db
    networks:
      - mongo-networks
    command: mongod --replSet replication
    depends_on:
      - mongo1
  mongo3:
    image: "mongo"
    ports:
      - "27022:27017"
    volumes:
      - $HOME/workspace/irqa-test/mongodb/db3:/data/db
    networks:
      - mongo-networks
    command: mongod --replSet replication
    depends_on:
      - mongo2
  mongosetup:
    image: "setup-rspl-mongo"
    depends_on:
      - mongo1
    networks:
      - mongo-networks

networks:
  mongo-networks:
    driver: bridge
