version: '3'
services:
  mongo1:
    image: "mongo"
    container_name: mongo1
    ports:
      - "27020:27017"
    volumes:
      - $HOME/workspace/irqa-test/mongodb/db1:/data/db
    networks:
      - mongo-networks
    command: mongod --replSet replication
  mongo2:
    image: "mongo"
    container_name: mongo2
    ports:
      - "27021:27017"
    volumes:
      - $HOME/workspace/irqa-test/mongodb/db2:/data/db
    networks:
      - mongo-networks
    command: mongod --replSet replication
    depends_on:
      - mongo1
  mongo3:
    image: "mongo"
    container_name: mongo3
    ports:
      - "27022:27017"
    volumes:
      - $HOME/workspace/irqa-test/mongodb/db3:/data/db
    networks:
      - mongo-networks
    command: mongod --replSet replication
    depends_on:
      - mongo2
  mongosetup:
    build: ./setup-image
    image: setup-rspl-mongo:lastest
    depends_on:
      - mongo1
    networks:
      - mongo-networks

networks:
  mongo-networks:
    driver: bridge